- name: Create target directory
  file:
    path: metrics
    state: directory
    mode: 0755


- name: copy docker compose
  copy:
    src: prometheus.yml
    dest: ./metrics/docker-compose.yml


# Prometheus
- name: Create config directory
  file:
    path: metrics/prometheus
    state: directory
    mode: 0755

- name: copy config file
  copy:
    src: prometheus/prometheus.yml
    dest: ./metrics/prometheus/prometheus.yml

- name: add metric configurations
  include_tasks: metrics_configuration.yml


# Grafana
- name: copy grafana folder
  copy:
    src: grafana
    dest: ./metrics
#    directory_mode: yes
    mode: 0755



- name: Tear down existing services
  community.docker.docker_compose:
    project_src: ./metrics
    state: absent
  become: true

- name: Create and start services
  community.docker.docker_compose:
    project_src: ./metrics
  register: output

- ansible.builtin.debug:
    var: output